// articleList
export const REQUEST_ARTICLES = 'REQUEST_ARTICLES'
export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES'
export const RECEIVE_ARTICLES_ERROR = 'RECEIVE_ARTICLES_ERROR'

// articleDetails
export const REQUEST_ARTICLE = 'REQUEST_ARTICLE'
export const RECEIVE_ARTICLE = 'RECEIVE_ARTICLE'
export const RECEIVE_ARTICLE_ERROR = 'RECEIVE_ARTICLE_ERROR'